<a href="https://colab.research.google.com/github/malavikasreekumar/Wine-Tester/blob/master/Wine_Tester.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [2]:
cd gdrive/My Drive

/content/gdrive/My Drive


In [0]:
import numpy as np
import pandas as pd
#df=pd.read_csv('winequality-red.csv')

dataset= pd.read_csv('winequality-red.csv')
X=dataset.iloc[:,[0,10]].values
y=dataset.iloc[:, 11].values

In [4]:
df.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [0]:
"""
#Loading data to X and y
X = df.values
y = df['quality'].values
#Dropping 'Survived' from X
X = np.delete(X, 11, axis=1)""

In [27]:
X

array([[ 7.4,  9.4],
       [ 7.8,  9.8],
       [ 7.8,  9.8],
       ...,
       [ 6.3, 11. ],
       [ 5.9, 10.2],
       [ 6. , 11. ]])

In [0]:
"""from sklearn.preprocessing import StandardScaler 
  

  
# Initialise the Scaler 
scaler = StandardScaler() 
  
# To scale data 
scaler.fit(df) """


#feature scaling
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.fit_transform(X_test)  


In [8]:
df.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [0]:
from sklearn.model_selection import  train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.17,random_state=0)

In [42]:
"""from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X_train,y_train)"""

from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
#y_pred=lr.predict(X_test)
#Predicting test results
y_pred=classifier.predict(X_test)

In [44]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
from sklearn import metrics
print("Accuracy=",metrics.accuracy_score(y_test, y_pred))

print(cm)



Accuracy= 0.6139705882352942
[[ 0  0  2  0  0  0]
 [ 0  0  6  2  0  0]
 [ 0  0 90 24  1  0]
 [ 0  0 43 75  2  0]
 [ 0  0  1 21  2  0]
 [ 0  0  0  3  0  0]]


In [52]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5,metric='manhattan')
knn.fit(X_train,y_train)
y_pred=knn.predict(X_test)
cmk=confusion_matrix(y_test,y_pred)
print("Accuracy=",metrics.accuracy_score(y_test, y_pred))

print(cmk)

Accuracy= 0.6029411764705882
[[ 0  0  1  1  0  0]
 [ 0  0  5  3  0  0]
 [ 0  0 88 24  3  0]
 [ 0  0 41 69 10  0]
 [ 0  0  3 14  7  0]
 [ 0  0  0  1  2  0]]


In [54]:
# Fitting classifier to the Training set
from sklearn.svm import SVC
svm=SVC(kernel='linear',random_state=0)
svm.fit(X_train,y_train)
# Create your classifier here

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cmsvm = confusion_matrix(y_test, y_pred)
print("Accuracy=",metrics.accuracy_score(y_test, y_pred))

print(cmsvm)

Accuracy= 0.6139705882352942
[[ 0  0  2  0  0  0]
 [ 0  0  6  2  0  0]
 [ 0  0 90 24  1  0]
 [ 0  0 43 75  2  0]
 [ 0  0  1 21  2  0]
 [ 0  0  0  3  0  0]]
